swagger: "2.0"
info:
  description: "Portfolio do Gustavo Honorato"
  version: "1.0.0"
  title: "Swagger Boleta de bndu"
  contact:
    email: "gustavo.honoratonic@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "127.0.0.1:8080"
basePath: "/v1"
tags:
  - name: "formations"
    description: "Operations about my formation"
schemes:
  - "https"
  - "http"
paths:
  /formations:
    get:
      tags:
        - "formations"
      summary: "Return a paginated list of my formations"
      description: "Return a paginated list of my formations"
      operationId: "get_formations"
      produces:
        - "application/json"
      parameters: []
      responses:
        200:
          description: "pong response"
      x-swagger-router-controller: "server.controllers.formations_controller"

definitions:
  Pagination:
    type: object
    properties:
      page:
        type: integer
        example: 2
      has_next:
        type: boolean
        example: false
      has_prev:
        type: boolean
        example: true
      next_num:
        type: integer
        example: 3
      pages:
        type: integer
        example: 100
      per_page:
        type: integer
        example: 50
      prev_num:
        type: integer
        example: 2
      total:
        type: integer
        example: 5000

parameters:
  page:
    name: "page"
    in: "query"
    required: false
    description: "Number of the page"
    type: "integer"
